{ config, colors }:
''
plugin location="file:${config.xdg.configHome}/zellij/plugins/zjstatus.wasm" {
    format_left   "{mode}"
    format_space  "#[bg=${colors.base00}]"
    format_hide_on_overlength "true"
    format_precedence "l"

    border_enabled  "false"
    hide_frame_for_single_pane "true"

    mode_normal        "#[fg=${colors.base0D},bg=${colors.base00}]#[bg=${colors.base0D},fg=${colors.base00},bold] NORMAL #[fg=${colors.base0D},bg=${colors.base01}]#[bg=${colors.base01},fg=${colors.base05}] #[fg=${colors.base0A},bold]Alt+t #[fg=${colors.base05}]tab #[fg=${colors.base0A},bold]Alt+n #[fg=${colors.base05}]pane #[fg=${colors.base0A},bold]Alt+h/j/k/l #[fg=${colors.base05}]nav #[fg=${colors.base09},bold]Alt+f #[fg=${colors.base09}]find #[fg=${colors.base0A},bold]Alt+w #[fg=${colors.base05}]float #[fg=${colors.base0A},bold]Alt+z #[fg=${colors.base05}]zoom #[fg=${colors.base0A},bold]Alt+s #[fg=${colors.base05}]sessions #[fg=${colors.base03}]| #[fg=${colors.base0A},bold]^f #[fg=${colors.base05}]sessionizer #[fg=${colors.base0A},bold]^p #[fg=${colors.base05}]pane #[fg=${colors.base0A},bold]^t #[fg=${colors.base05}]tab #[fg=${colors.base0A},bold]^s #[fg=${colors.base05}]scroll #[fg=${colors.base0A},bold]^o #[fg=${colors.base05}]session #[fg=${colors.base0A},bold]^g #[fg=${colors.base05}]lock #[fg=${colors.base01},bg=${colors.base00}]"
    mode_locked        "#[fg=${colors.base08},bg=${colors.base00}]#[bg=${colors.base08},fg=${colors.base00},bold] LOCKED  #[fg=${colors.base08},bg=${colors.base01}]#[bg=${colors.base01},fg=${colors.base05}] #[fg=${colors.base0A},bold]^g #[fg=${colors.base05}]unlock #[fg=${colors.base01},bg=${colors.base00}]"
    mode_pane          "#[fg=${colors.base0B},bg=${colors.base00}]#[bg=${colors.base0B},fg=${colors.base00},bold] PANE #[fg=${colors.base0B},bg=${colors.base01}]#[bg=${colors.base01},fg=${colors.base05}] #[fg=${colors.base0A},bold]h/j/k/l #[fg=${colors.base05}]move #[fg=${colors.base0A},bold]n/d/r #[fg=${colors.base05}]new #[fg=${colors.base0A},bold]x #[fg=${colors.base05}]close #[fg=${colors.base0A},bold]f #[fg=${colors.base05}]fullscreen #[fg=${colors.base0A},bold]w #[fg=${colors.base05}]floating #[fg=${colors.base0A},bold]c #[fg=${colors.base05}]rename #[fg=${colors.base01},bg=${colors.base00}]"
    mode_tab           "#[fg=${colors.base0D},bg=${colors.base00}]#[bg=${colors.base0D},fg=${colors.base00},bold] TAB #[fg=${colors.base0D},bg=${colors.base01}]#[bg=${colors.base01},fg=${colors.base05}] #[fg=${colors.base0A},bold]h/l #[fg=${colors.base05}]move #[fg=${colors.base0A},bold]1..9 #[fg=${colors.base05}]go #[fg=${colors.base0A},bold]n #[fg=${colors.base05}]new #[fg=${colors.base0A},bold]x #[fg=${colors.base05}]close #[fg=${colors.base0A},bold]r #[fg=${colors.base05}]rename #[fg=${colors.base0A},bold]s #[fg=${colors.base05}]sync #[fg=${colors.base01},bg=${colors.base00}]"
    mode_scroll        "#[fg=${colors.base0C},bg=${colors.base00}]#[bg=${colors.base0C},fg=${colors.base00},bold] SCROLL #[fg=${colors.base0C},bg=${colors.base01}]#[bg=${colors.base01},fg=${colors.base05}] #[fg=${colors.base0A},bold]j/k #[fg=${colors.base05}]scroll #[fg=${colors.base0A},bold]d/u #[fg=${colors.base05}]half #[fg=${colors.base09},bold]e #[fg=${colors.base09}]neovim #[fg=${colors.base0A},bold]/ #[fg=${colors.base05}]search #[fg=${colors.base0A},bold]q #[fg=${colors.base05}]exit #[fg=${colors.base01},bg=${colors.base00}]"
    mode_enter_search  "#[fg=${colors.base0E},bg=${colors.base00}]#[bg=${colors.base0E},fg=${colors.base00},bold] SEARCH #[fg=${colors.base0E},bg=${colors.base01}]#[bg=${colors.base01},fg=${colors.base05}] #[fg=${colors.base05}]enter query #[fg=${colors.base01},bg=${colors.base00}]"
    mode_search        "#[fg=${colors.base0E},bg=${colors.base00}]#[bg=${colors.base0E},fg=${colors.base00},bold] SEARCH #[fg=${colors.base0E},bg=${colors.base01}]#[bg=${colors.base01},fg=${colors.base05}] #[fg=${colors.base0A},bold]n/p #[fg=${colors.base05}]next/prev #[fg=${colors.base0A},bold]c #[fg=${colors.base05}]case #[fg=${colors.base0A},bold]w #[fg=${colors.base05}]wrap #[fg=${colors.base0A},bold]q #[fg=${colors.base05}]exit #[fg=${colors.base01},bg=${colors.base00}]"
    mode_session       "#[fg=${colors.base09},bg=${colors.base00}]#[bg=${colors.base09},fg=${colors.base00},bold] SESSION #[fg=${colors.base09},bg=${colors.base01}]#[bg=${colors.base01},fg=${colors.base05}] #[fg=${colors.base0A},bold]d #[fg=${colors.base05}]detach #[fg=${colors.base0A},bold]w #[fg=${colors.base05}]manager #[fg=${colors.base09},bold]f/s #[fg=${colors.base09}]sessionizer #[fg=${colors.base0A},bold]q #[fg=${colors.base05}]quit #[fg=${colors.base01},bg=${colors.base00}]"
    mode_resize        "#[fg=${colors.base0A},bg=${colors.base00}]#[bg=${colors.base0A},fg=${colors.base00},bold] RESIZE #[fg=${colors.base0A},bg=${colors.base01}]#[bg=${colors.base01},fg=${colors.base05}] #[fg=${colors.base0A},bold]h/j/k/l #[fg=${colors.base05}]resize #[fg=${colors.base0A},bold]+/- #[fg=${colors.base05}]inc/dec #[fg=${colors.base01},bg=${colors.base00}]"
    mode_move          "#[fg=${colors.base0A},bg=${colors.base00}]#[bg=${colors.base0A},fg=${colors.base00},bold] MOVE #[fg=${colors.base0A},bg=${colors.base01}]#[bg=${colors.base01},fg=${colors.base05}] #[fg=${colors.base0A},bold]h/j/k/l #[fg=${colors.base05}]move #[fg=${colors.base01},bg=${colors.base00}]"
    mode_tmux          "#[fg=${colors.base0E},bg=${colors.base00}]#[bg=${colors.base0E},fg=${colors.base00},bold] TMUX #[fg=${colors.base0E},bg=${colors.base01}]#[bg=${colors.base01},fg=${colors.base05}] #[fg=${colors.base09},bold]f #[fg=${colors.base09}]sessionizer #[fg=${colors.base0A},bold][ #[fg=${colors.base05}]scroll #[fg=${colors.base0A},bold]\"/% #[fg=${colors.base05}]split #[fg=${colors.base0A},bold]z #[fg=${colors.base05}]zoom #[fg=${colors.base0A},bold]d #[fg=${colors.base05}]detach #[fg=${colors.base01},bg=${colors.base00}]"
}
''
